# Basic
title: Ethan
subtitle: 今天我所做的一切都是为了装逼！
welcome_message: Welcome! 
description: 嗨，我是一个程序员。
creator: <a href="https://ethan-9606.github.io">@Ethan</a>

url: "https://ethan-9606.github.io"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: Ethan's GitHub,    url: 'https://github.com/Ethan-9606'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 GcsSloop,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: GcsSloop
    # duoshuo:
# Social
social:
    weibo: qingyan0000
    github: Ethan-9606
    mail: zss9606@126.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: www.gcssloop.com
